export {
  AmazonIcon,
  FacebookIcon,
  FigmaIcon,
  GitHubIcon,
  GoogleAdsIcon,
  GoogleIcon,
  type IconComponent,
  InstagramIcon,
  LinkedInIcon,
  MetaIcon,
  makeSvgIcon,
  ThreadsIcon,
  TikTokIcon,
  XIcon,
  YouTubeIcon,
} from './brandIcon';
