import type {
  OrganicActivityItem,
  OrganicCalendarDay,
  OrganicCreationStep,
  OrganicEditorSlide,
  OrganicTrendType,
} from "./types"

export const organicCreationSteps: OrganicCreationStep[] = [
  {
    id: "trends",
    title: "Trends",
    detail: "Select 3 trends to ground the week",
    status: "complete",
  },
  {
    id: "competitors",
    title: "Competitors",
    detail: "Tag 4 posts to anchor tone",
    status: "complete",
  },
  {
    id: "agent",
    title: "Agent reception",
    detail: "Streaming drafts and timing suggestions",
    status: "active",
  },
  {
    id: "composer",
    title: "Draft composer",
    detail: "Edit, schedule, and multi-post",
    status: "upcoming",
  },
]

export const organicTrendTypes: OrganicTrendType[] = [
  {
    id: "industry",
    label: "Industry",
    groups: [
      {
        id: "industry-rising",
        title: "Rising signals",
        trends: [
          {
            id: "trend-1",
            title: "Vertical video for B2B",
            summary: "Short-form demos are outperforming static posts in SaaS onboarding funnels.",
            momentum: "rising",
            tags: ["format", "b2b"],
          },
          {
            id: "trend-2",
            title: "Proof-based launch threads",
            summary: "Founders are pairing launch posts with data-driven results within 48 hours.",
            momentum: "rising",
            tags: ["launch", "metrics"],
          },
        ],
      },
      {
        id: "industry-steady",
        title: "Steady performers",
        trends: [
          {
            id: "trend-3",
            title: "Customer voice quotes",
            summary: "Carousel slides that highlight a single quote + metric continue to drive saves.",
            momentum: "stable",
            tags: ["testimonial", "carousel"],
          },
        ],
      },
    ],
  },
  {
    id: "platform",
    label: "Platform",
    groups: [
      {
        id: "platform-rising",
        title: "Platform moves",
        trends: [
          {
            id: "trend-4",
            title: "LinkedIn carousel reposts",
            summary: "Carousel reshares with added commentary are getting higher dwell time.",
            momentum: "rising",
            tags: ["linkedin", "carousel"],
          },
          {
            id: "trend-5",
            title: "Instagram reel cover text",
            summary: "Readable cover titles are improving retention on reels by 12-18%.",
            momentum: "rising",
            tags: ["instagram", "reel"],
          },
        ],
      },
      {
        id: "platform-steady",
        title: "Baseline tactics",
        trends: [
          {
            id: "trend-6",
            title: "CTA overlays",
            summary: "Short CTAs on slide 3 keep swipe completion above 70%.",
            momentum: "stable",
            tags: ["cta", "design"],
          },
        ],
      },
    ],
  },
  {
    id: "audience",
    label: "Audience",
    groups: [
      {
        id: "audience-rising",
        title: "Audience demand",
        trends: [
          {
            id: "trend-7",
            title: "Behind-the-scenes builds",
            summary: "Creators want the build story, especially for product + team visibility.",
            momentum: "rising",
            tags: ["culture", "story"],
          },
        ],
      },
      {
        id: "audience-cooling",
        title: "Cooling topics",
        trends: [
          {
            id: "trend-8",
            title: "Weekly recap threads",
            summary: "Week-in-review posts trend higher when paired with a single metric.",
            momentum: "cooling",
            tags: ["recap", "weekly"],
          },
        ],
      },
    ],
  },
]

export const organicCalendarDays: OrganicCalendarDay[] = [
  {
    id: "2026-01-05",
    label: "Mon",
    dateLabel: "Jan 5",
    suggestedTimes: ["9:30 AM", "1:00 PM", "6:15 PM"],
    slots: [
      {
        id: "draft-001",
        title: "Product tour carousel",
        summary: "Five-slide walkthrough of the new onboarding flow.",
        timeLabel: "9:30 AM",
        dateLabel: "Mon, Jan 5",
        status: "scheduled",
        platforms: ["instagram", "linkedin"],
        format: "Carousel",
        objective: "Educate",
        slideCount: 5,
        captionPreview: "A fast tour of the onboarding flow with the moments that convert.",
        tags: ["onboarding", "product"],
        location: "Austin, TX",
        mediaCount: 5,
      },
      {
        id: "draft-002",
        title: "Founder story clip",
        summary: "Short reel focusing on why the product exists.",
        timeLabel: "1:00 PM",
        dateLabel: "Mon, Jan 5",
        status: "draft",
        platforms: ["instagram"],
        format: "Reel",
        objective: "Awareness",
        captionPreview: "Why we built Continuum and the moment that changed the roadmap.",
        tags: ["founder", "story"],
        mediaCount: 1,
      },
    ],
  },
  {
    id: "2026-01-06",
    label: "Tue",
    dateLabel: "Jan 6",
    suggestedTimes: ["10:00 AM", "2:15 PM"],
    slots: [
      {
        id: "draft-003",
        title: "Weekly trend briefing",
        summary: "High signal trends with a clear CTA.",
        timeLabel: "10:00 AM",
        dateLabel: "Tue, Jan 6",
        status: "streaming",
        platforms: ["linkedin"],
        format: "Article",
        objective: "Authority",
        slideCount: 0,
        progress: 62,
        captionPreview: "This week is about actionable signals, not noise.",
        tags: ["trends", "briefing"],
        mediaCount: 1,
      },
      {
        id: "draft-004",
        title: "Customer proof tiles",
        summary: "Carousel highlighting three client wins.",
        timeLabel: "2:15 PM",
        dateLabel: "Tue, Jan 6",
        status: "draft",
        platforms: ["instagram"],
        format: "Carousel",
        objective: "Trust",
        slideCount: 4,
        captionPreview: "Three wins from the teams moving fastest this week.",
        tags: ["testimonials", "results"],
        mediaCount: 4,
      },
    ],
  },
  {
    id: "2026-01-07",
    label: "Wed",
    dateLabel: "Jan 7",
    suggestedTimes: ["11:20 AM", "4:40 PM"],
    slots: [
      {
        id: "draft-005",
        title: "Launch checklist",
        summary: "Single image with checklist overlay.",
        timeLabel: "11:20 AM",
        dateLabel: "Wed, Jan 7",
        status: "scheduled",
        platforms: ["instagram", "linkedin"],
        format: "Static",
        objective: "Conversion",
        captionPreview: "Your launch checklist in 7 bullet points.",
        tags: ["launch", "checklist"],
        mediaCount: 1,
      },
      {
        id: "draft-006",
        title: "Competitor breakdown",
        summary: "Insightful teardown from agent reception.",
        timeLabel: "4:40 PM",
        dateLabel: "Wed, Jan 7",
        status: "placeholder",
        platforms: ["linkedin"],
        format: "Article",
        objective: "Insights",
        captionPreview: "Waiting for agent reception to complete.",
        tags: ["analysis", "competitors"],
        progress: 24,
        mediaCount: 0,
      },
    ],
  },
  {
    id: "2026-01-08",
    label: "Thu",
    dateLabel: "Jan 8",
    suggestedTimes: ["9:45 AM", "3:10 PM"],
    slots: [
      {
        id: "draft-007",
        title: "Behind the scenes",
        summary: "Team culture reel with caption notes.",
        timeLabel: "9:45 AM",
        dateLabel: "Thu, Jan 8",
        status: "draft",
        platforms: ["instagram"],
        format: "Reel",
        objective: "Affinity",
        captionPreview: "Inside the studio: what we are building this week.",
        tags: ["culture", "studio"],
        mediaCount: 1,
      },
      {
        id: "draft-008",
        title: "Platform tips",
        summary: "LinkedIn article with 5 tactics.",
        timeLabel: "3:10 PM",
        dateLabel: "Thu, Jan 8",
        status: "scheduled",
        platforms: ["linkedin"],
        format: "Article",
        objective: "Education",
        captionPreview: "Five tactics to keep posts consistent without losing voice.",
        tags: ["tips", "linkedin"],
        mediaCount: 1,
      },
    ],
  },
  {
    id: "2026-01-09",
    label: "Fri",
    dateLabel: "Jan 9",
    suggestedTimes: ["12:30 PM", "5:00 PM"],
    slots: [
      {
        id: "draft-009",
        title: "Weekly recap",
        summary: "Carousel recap of the week highlights.",
        timeLabel: "12:30 PM",
        dateLabel: "Fri, Jan 9",
        status: "draft",
        platforms: ["instagram", "linkedin"],
        format: "Carousel",
        objective: "Retention",
        slideCount: 6,
        captionPreview: "A recap of everything the team shipped this week.",
        tags: ["recap", "weekly"],
        mediaCount: 6,
      },
      {
        id: "draft-010",
        title: "Ask the audience",
        summary: "Prompting comments for next week.",
        timeLabel: "5:00 PM",
        dateLabel: "Fri, Jan 9",
        status: "draft",
        platforms: ["instagram"],
        format: "Static",
        objective: "Engagement",
        captionPreview: "Tell us what you want to see in next week's build.",
        tags: ["community", "prompt"],
        mediaCount: 1,
      },
    ],
  },
  {
    id: "2026-01-10",
    label: "Sat",
    dateLabel: "Jan 10",
    suggestedTimes: ["10:10 AM"],
    slots: [
      {
        id: "draft-011",
        title: "Creative exploration",
        summary: "Experimental carousel with new visuals.",
        timeLabel: "10:10 AM",
        dateLabel: "Sat, Jan 10",
        status: "draft",
        platforms: ["instagram"],
        format: "Carousel",
        objective: "Experiment",
        slideCount: 4,
        captionPreview: "Testing a new visual system for the next drop.",
        tags: ["experiment", "design"],
        mediaCount: 4,
      },
    ],
  },
  {
    id: "2026-01-11",
    label: "Sun",
    dateLabel: "Jan 11",
    suggestedTimes: ["4:00 PM"],
    slots: [
      {
        id: "draft-012",
        title: "Planning pulse",
        summary: "Short post to set next week's theme.",
        timeLabel: "4:00 PM",
        dateLabel: "Sun, Jan 11",
        status: "draft",
        platforms: ["linkedin"],
        format: "Text",
        objective: "Alignment",
        captionPreview: "Next week focuses on clarity in scheduling and scaling.",
        tags: ["planning", "weekly"],
        mediaCount: 0,
      },
    ],
  },
]

export const organicActivityFeed: OrganicActivityItem[] = [
  {
    id: "activity-01",
    actor: "Danilo Sousa",
    summary: "Approved draft draft-001 for crosspost.",
    timeLabel: "Jun 21, 11:34 AM",
    highlight: "Approved",
  },
  {
    id: "activity-02",
    actor: "Zahra Ambessa",
    summary: "Purchased 3 new template bundles.",
    timeLabel: "Jun 21, 9:43 AM",
  },
  {
    id: "activity-03",
    actor: "Zahra Ambessa",
    summary: "Responded to competitor insight #7514.",
    timeLabel: "Jun 21, 9:41 AM",
  },
  {
    id: "activity-04",
    actor: "Jasper Eriksson",
    summary: "Created 4 placeholder slots for next week.",
    timeLabel: "Jun 20, 4:55 PM",
    highlight: "Queued",
  },
]

export const organicEditorSlides: OrganicEditorSlide[] = [
  {
    id: "slide-1",
    label: "Slide 1",
    gradient: "from-slate-900 via-slate-800 to-indigo-500/60",
  },
  {
    id: "slide-2",
    label: "Slide 2",
    gradient: "from-emerald-900 via-emerald-700 to-emerald-500/60",
  },
  {
    id: "slide-3",
    label: "Slide 3",
    gradient: "from-indigo-900 via-violet-800 to-violet-500/60",
  },
  {
    id: "slide-4",
    label: "Slide 4",
    gradient: "from-amber-900 via-orange-700 to-amber-500/60",
  },
  {
    id: "slide-5",
    label: "Slide 5",
    gradient: "from-slate-900 via-slate-700 to-sky-500/60",
  },
]
