"use client"

import * as React from "react"
import Image from "next/image"
import { ChevronLeftIcon, ChevronRightIcon, Cross2Icon, PlayIcon } from "@radix-ui/react-icons"

import { Loader2, Send } from "lucide-react"

import { cn } from "@/lib/utils"
import type { OrganicCalendarDraft } from "./types"
import { useCalendarStore } from "@/lib/organic/store"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { isOrganicPlatformKey } from "@/lib/organic/platforms"
import {
  resolvePreviewAspectRatio,
  resolvePreviewMaxWidth,
} from "./social-preview-utils"
import { OrganicCreativesPicker } from "./OrganicCreativesPicker"
import { HyperFramePlayer } from "./HyperFramePlayer"
import { usePublishDraft } from "@/components/organic/hooks/usePublishDraft"
import { signMediaAsset, signOrganicMediaAsset } from "@/lib/organic/hyperframeSign"

interface OrganicDraftPreviewProps {
  draft: OrganicCalendarDraft
  brandName?: string
  brandProfileId?: string
  onApprove?: (draftId: string) => void
}

type SocialPreviewProps = {
  draft: OrganicCalendarDraft
  mediaAspectRatio: number
  onCaptionChange: (value: string) => void
  thumbnailDirection: string
  brandName?: string
}

function hasText(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0
}

function brandInitials(name: string | undefined): string {
  if (!name) return "BR"
  return name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2)
    .toUpperCase()
}

// Storage-first: the preview always resolves to a storage signed URL (durable +
// re-signable), never an in-memory base64 data: URL. Generated bytes live in the
// media-library bucket; the draft carries publishingAssets (storageUrl, refreshed
// by useDraftWithFreshMedia) and/or mediaSuggestion.assetUrl.
function resolveDraftMediaAssetUrl(draft: OrganicCalendarDraft): string | null {
  const persistedImageAsset = draft.publishingAssets?.find((asset) => asset.kind === "image")
  if (hasText(persistedImageAsset?.storageUrl)) {
    return persistedImageAsset.storageUrl
  }

  const assetUrl = draft.mediaSuggestion?.assetUrl
  return hasText(assetUrl) ? assetUrl.trim() : null
}

function resolveDraftMediaAltText(draft: OrganicCalendarDraft): string {
  const candidate =
    typeof draft.mediaSuggestion?.alt === "string"
      ? draft.mediaSuggestion.alt.trim()
      : ""
  if (candidate.length > 0) return candidate
  return draft.title || "Generated draft image"
}

function resolveCreativeDirection(draft: OrganicCalendarDraft): string {
  return (
    draft.creativeDirectionPrompt?.trim() ||
    draft.creativeIdea?.trim() ||
    draft.summary?.trim() ||
    draft.title
  )
}

function resolveThumbnailDirection(draft: OrganicCalendarDraft): string {
  return (
    draft.thumbnailPrompt?.trim() ||
    draft.mediaSuggestion?.prompt?.trim() ||
    draft.assetHints?.[0]?.suggestion?.trim() ||
    ""
  )
}

function resolveCarouselSlides(draft: OrganicCalendarDraft): string[] {
  // Storage-first: carousel slides are durable published assets (storageUrl,
  // refreshed by useDraftWithFreshMedia), ordered by slideIndex. No base64.
  const published = (draft.publishingAssets ?? [])
    .filter((a) => a.kind === "image" && hasText(a.storageUrl))
    .sort((a, b) => (a.slideIndex ?? 999) - (b.slideIndex ?? 999))
  if (published.length > 0) {
    return published.map((a) => a.storageUrl)
  }

  const primary = resolveDraftMediaAssetUrl(draft)
  return primary ? [primary] : []
}

function CarouselMediaArea({
  slides,
  alt,
  aspectRatio,
  borderClass = "border-b border-border/70",
}: {
  slides: string[]
  alt: string
  aspectRatio: number
  borderClass?: string
}) {
  const [activeIndex, setActiveIndex] = React.useState(0)
  const total = slides.length

  if (total === 0) {
    return (
      <div className={cn("relative bg-muted", borderClass)} style={{ aspectRatio }}>
        <div className="absolute inset-0 flex items-center justify-center text-muted-foreground">
          <div className="flex flex-col items-center gap-2 text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full border border-border/70 bg-background">
              <PlayIcon className="h-6 w-6" />
            </div>
            <p className="text-xs">No thumbnail yet</p>
          </div>
        </div>
      </div>
    )
  }

  const canPrev = activeIndex > 0
  const canNext = activeIndex < total - 1

  return (
    <div className={cn("relative bg-muted", borderClass)} style={{ aspectRatio }}>
      <Image
        src={slides[activeIndex]}
        alt={`${alt} — slide ${activeIndex + 1}`}
        fill
        unoptimized
        sizes="(max-width: 768px) 100vw, 560px"
        className="absolute inset-0 h-full w-full object-cover"
      />

      {total > 1 && (
        <div className="absolute right-2 top-2 rounded-full bg-black/50 px-2 py-0.5 text-[10px] font-semibold text-white tabular-nums">
          {activeIndex + 1}/{total}
        </div>
      )}

      {canPrev && (
        <button
          type="button"
          onClick={() => setActiveIndex((i) => i - 1)}
          className="absolute left-2 top-1/2 flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-full bg-black/40 text-white transition-colors hover:bg-black/60"
          aria-label="Previous slide"
        >
          <ChevronLeftIcon className="h-4 w-4" />
        </button>
      )}
      {canNext && (
        <button
          type="button"
          onClick={() => setActiveIndex((i) => i + 1)}
          className="absolute right-2 top-1/2 flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-full bg-black/40 text-white transition-colors hover:bg-black/60"
          aria-label="Next slide"
        >
          <ChevronRightIcon className="h-4 w-4" />
        </button>
      )}

      {total > 1 && (
        <div className="absolute bottom-2 left-1/2 flex -translate-x-1/2 items-center gap-1">
          {slides.map((_, i) => (
            <button
              key={i}
              type="button"
              onClick={() => setActiveIndex(i)}
              className={cn(
                "h-1.5 rounded-full transition-all",
                i === activeIndex ? "w-4 bg-white" : "w-1.5 bg-white/50"
              )}
              aria-label={`Slide ${i + 1}`}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// All user-supplied text is HTML-escaped before being inserted into the HTML
// string, so dangerouslySetInnerHTML on the mirror div is XSS-safe. The only
// injected tags are the hardcoded <mark> wrapper and <br> — never user content.
function buildCaptionMirrorHtml(text: string): string {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return escaped
    .replace(/@[^\s\n@&]+/g, '<mark class="mention-token">$&</mark>')
    .replace(/\n/g, "<br>");
}

function InlinePreviewTextarea({
  className,
  value,
  onScroll,
  ...props
}: React.ComponentProps<typeof Textarea>) {
  const mirrorRef = React.useRef<HTMLDivElement>(null);

  const mirrorHtml = React.useMemo(
    () => buildCaptionMirrorHtml(String(value ?? "")),
    [value]
  );

  const handleScroll = React.useCallback(
    (e: React.UIEvent<HTMLTextAreaElement>) => {
      if (mirrorRef.current) mirrorRef.current.scrollTop = e.currentTarget.scrollTop;
      onScroll?.(e);
    },
    [onScroll]
  );

  // px-3 py-2 matches the Textarea base padding; className overrides (e.g. p-0) apply to both
  const layoutClass = cn("px-3 py-2", className);

  return (
    <div className="relative">
      <div
        ref={mirrorRef}
        aria-hidden
        className={cn(
          layoutClass,
          "pointer-events-none absolute inset-0 overflow-hidden whitespace-pre-wrap break-words text-transparent"
        )}
        dangerouslySetInnerHTML={{ __html: mirrorHtml }}
      />
      <Textarea
        value={value}
        onScroll={handleScroll}
        {...props}
        className={cn(
          "relative resize-none border-border/60 bg-transparent text-foreground placeholder:text-muted-foreground shadow-none focus-visible:ring-1 focus-visible:ring-ring/40",
          className
        )}
      />
    </div>
  )
}

const LIFECYCLE_STEPS = [
  { key: "draft", label: "Draft" },
  { key: "scheduled", label: "Scheduled" },
  { key: "posted", label: "Posted" },
] as const

function LifecyclePill({ status }: { status: OrganicCalendarDraft["status"] }) {
  const activeIndex =
    status === "published" ? 2 : status === "scheduled" ? 1 : 0

  return (
    <div className="flex items-center gap-1 w-full">
      {LIFECYCLE_STEPS.map((step, i) => {
        const isActive = i === activeIndex
        const isCompleted = i < activeIndex
        const isFuture = i > activeIndex
        return (
          <React.Fragment key={step.key}>
            {i > 0 && <div className="h-px flex-1 bg-border/50" />}
            <span
              className={cn(
                "rounded-full px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider",
                isActive && status === "failed"
                  ? "border border-destructive/40 bg-destructive/10 text-destructive"
                  : isActive
                    ? "border border-primary/30 bg-primary/10 text-primary"
                    : isCompleted
                      ? "border border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-400"
                      : isFuture && step.key === "posted"
                        ? "border border-border/50 bg-muted/30 text-muted-foreground/40"
                        : "border border-border/50 bg-muted/40 text-muted-foreground/60"
              )}
            >
              {step.label}
            </span>
          </React.Fragment>
        )
      })}
    </div>
  )
}

function toPublishFormat(format: string): "Post" | "Carousel" | "Reel" | "HyperFrame" {
  const f = format.toLowerCase()
  if (f === "hyperframe") return "HyperFrame"
  if (f === "reel" || f === "video") return "Reel"
  if (f === "carousel") return "Carousel"
  return "Post"
}

function HashtagInput({ onAdd }: { onAdd: (tag: string) => void }) {
  const [value, setValue] = React.useState("")

  const handleSubmit = () => {
    const cleaned = value.trim().replace(/^#/, "")
    if (!cleaned) return
    onAdd(cleaned)
    setValue("")
  }

  return (
    <div className="flex items-center gap-1.5">
      <input
        type="text"
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") { e.preventDefault(); handleSubmit() }
        }}
        placeholder="Add hashtag..."
        className="h-6 flex-1 rounded border border-border/50 bg-transparent px-2 text-[10px] text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-1 focus:ring-ring"
      />
      <button
        type="button"
        onClick={handleSubmit}
        disabled={!value.trim()}
        className="rounded bg-muted/60 px-2 py-0.5 text-[10px] font-medium text-muted-foreground hover:bg-muted disabled:opacity-40"
      >
        Add
      </button>
    </div>
  )
}

/**
 * Re-signs the draft's durable publishing assets on read. Persisted drafts store
 * only bucket+storagePath (the upload-time signed URL expires in ~1h), so this
 * mints fresh storageUrls when the preview opens. Non-blocking: the initial render
 * uses the stored storageUrl, then swaps to the refreshed URL when it arrives.
 */
function useDraftWithFreshMedia(
  draft: OrganicCalendarDraft,
  brandProfileId?: string,
): OrganicCalendarDraft {
  const [freshByPath, setFreshByPath] = React.useState<Record<string, string>>({})

  const signables = React.useMemo(
    () =>
      (draft.publishingAssets ?? []).filter(
        (a) => hasText(a.storagePath) && (hasText(a.assetId) || hasText(a.bucket)),
      ),
    [draft.publishingAssets],
  )

  React.useEffect(() => {
    if (!brandProfileId || signables.length === 0) return
    let cancelled = false
    void Promise.all(
      signables.map(async (asset) => {
        // Prefer the media-library registry id (durable handle) → /api/library/sign;
        // fall back to bucket+path re-sign for assets not yet registered.
        const url = hasText(asset.assetId)
          ? await signMediaAsset({ brandId: brandProfileId, assetId: asset.assetId })
          : await signOrganicMediaAsset({
              brandId: brandProfileId,
              bucket: asset.bucket as string,
              path: asset.storagePath,
            })
        return url ? ([asset.storagePath, url] as const) : null
      }),
    ).then((pairs) => {
      if (cancelled) return
      const next: Record<string, string> = {}
      for (const pair of pairs) if (pair) next[pair[0]] = pair[1]
      if (Object.keys(next).length > 0) setFreshByPath(next)
    })
    return () => {
      cancelled = true
    }
  }, [brandProfileId, signables])

  return React.useMemo(() => {
    if (Object.keys(freshByPath).length === 0 || !draft.publishingAssets) return draft
    return {
      ...draft,
      publishingAssets: draft.publishingAssets.map((asset) =>
        freshByPath[asset.storagePath] ? { ...asset, storageUrl: freshByPath[asset.storagePath] } : asset,
      ),
    }
  }, [draft, freshByPath])
}

export function OrganicDraftPreview({ draft, brandName, brandProfileId, onApprove }: OrganicDraftPreviewProps) {
  const updateDraft = useCalendarStore((state) => state.updateDraft)
  const draftForPreview = useDraftWithFreshMedia(draft, brandProfileId)
  const isHyperframeFormat = draft.format.toLowerCase() === "hyperframe"
  const selectedPlatform = draft.platforms[0] || "instagram"
  const previewMaxWidth = resolvePreviewMaxWidth(selectedPlatform)
  const mediaAspectRatio = resolvePreviewAspectRatio(selectedPlatform, draft.format)
  const creativeDirection = resolveCreativeDirection(draft)
  const thumbnailDirection = resolveThumbnailDirection(draft)

  const patchDraft = React.useCallback(
    (patch: Partial<OrganicCalendarDraft>) => {
      updateDraft(draft.id, (current) => ({
        ...current,
        ...patch,
      }))
    },
    [draft.id, updateDraft]
  )

  const isApproveDisabled =
    draft.status === "scheduled" || draft.status === "streaming"

  const handleCaptionChange = React.useCallback(
    (value: string) => patchDraft({ captionPreview: value }),
    [patchDraft]
  )

  const { publish, isPublishing, stage, pollingAttempt, tokenExpired } = usePublishDraft()
  const isInstagram = draft.platforms.includes("instagram")
  const isPublished = draft.status === "published"
  const canPublish = isInstagram && !isPublished && draft.status !== "streaming"
  const showFooter = onApprove != null || canPublish || isPublished

  return (
    <div className="flex h-full flex-col overflow-hidden rounded-xl border border-border/80 bg-card shadow-sm">
      {/* Header */}
      <div className="flex shrink-0 flex-col gap-2 border-b border-border/70 bg-muted/55 p-3">
        <div className="flex flex-wrap items-center gap-2">
          <Select
            value={selectedPlatform}
            onValueChange={(value) => {
              if (!isOrganicPlatformKey(value)) return
              patchDraft({ platforms: [value] })
            }}
          >
            <SelectTrigger className="h-8 w-[9.5rem] border-border/60 bg-background text-xs font-semibold">
              <SelectValue placeholder="Platform" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="instagram">Instagram</SelectItem>
              <SelectItem value="facebook">Facebook</SelectItem>
              <SelectItem value="linkedin">LinkedIn</SelectItem>
            </SelectContent>
          </Select>

          <Input
            value={draft.timeLabel}
            onChange={(event) => patchDraft({ timeLabel: event.target.value })}
            placeholder="9:00 AM"
            className="h-8 w-[8rem] border-border/60 bg-background text-xs font-medium"
          />

          <Select
            value={toPublishFormat(draft.format)}
            onValueChange={(value) => patchDraft({ format: value })}
          >
            <SelectTrigger className="h-8 w-[7rem] border-border/60 bg-background text-xs font-semibold">
              <SelectValue placeholder="Format" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="Post">Post</SelectItem>
              <SelectItem value="Carousel">Carousel</SelectItem>
              <SelectItem value="Reel">Reel</SelectItem>
              <SelectItem value="HyperFrame">HyperFrame</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <LifecyclePill status={draft.status} />
      </div>

      {/* Scroll content: Creative direction first, then social preview */}
      <ScrollArea className="flex-1 bg-muted/10 p-3">
        <div className="mx-auto flex w-full max-w-[48rem] flex-col gap-3">
          {/* Creative direction — primary edit field */}
          <div
            className="mx-auto w-full rounded-xl border border-border/70 bg-background/90 p-3"
            style={{ maxWidth: `${previewMaxWidth}px` }}
          >
            <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
              Creative direction prompt
            </p>
            <InlinePreviewTextarea
              value={creativeDirection}
              onChange={(event) =>
                patchDraft({
                  creativeDirectionPrompt: event.target.value,
                  creativeIdea: event.target.value,
                })
              }
              placeholder="Describe the hook, visual intent, and mood."
              className="min-h-[5.25rem] text-sm leading-relaxed"
            />
          </div>

          {/* Creatives — attach AI Studio assets */}
          {brandProfileId && (
            <div
              className="mx-auto w-full rounded-xl border border-border/70 bg-background/90 p-3"
              style={{ maxWidth: `${previewMaxWidth}px` }}
            >
              <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                Creatives
              </p>
              <OrganicCreativesPicker
                brandProfileId={brandProfileId}
                draftId={draft.id}
                attached={draft.publishingAssets ?? []}
                onAttach={(assets) =>
                  updateDraft(draft.id, (current) => ({
                    ...current,
                    publishingAssets: assets,
                  }))
                }
              />
            </div>
          )}

          {/* Hashtag Tiers */}
          {draft.hashtags && (draft.hashtags.high?.length || draft.hashtags.medium?.length || draft.hashtags.low?.length) ? (
            <div
              className="mx-auto w-full rounded-xl border border-border/70 bg-background/90 p-3"
              style={{ maxWidth: `${previewMaxWidth}px` }}
            >
              <div className="space-y-2">
                <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                  Hashtags
                </p>
                {(["high", "medium", "low"] as const).map((tier) => {
                  const tags = draft.hashtags?.[tier]
                  if (!tags?.length) return null
                  return (
                    <div key={tier} className="space-y-1">
                      <p className="text-[10px] font-medium text-muted-foreground/70">
                        {tier === "high" ? "High Competition" : tier === "medium" ? "Medium Competition" : "Low Competition"}
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {tags.map((tag) => (
                          <span
                            key={tag}
                            className="inline-flex items-center gap-1 rounded-full bg-muted/60 px-2 py-0.5 text-[10px] text-muted-foreground"
                          >
                            #{tag.replace(/^#/, "")}
                            <button
                              type="button"
                              className="ml-0.5 rounded-full p-0.5 text-muted-foreground/50 hover:bg-destructive/10 hover:text-destructive"
                              onClick={(e) => {
                                e.stopPropagation()
                                patchDraft({
                                  hashtags: {
                                    ...draft.hashtags,
                                    [tier]: tags.filter((t) => t !== tag),
                                  },
                                })
                              }}
                              aria-label={`Remove #${tag.replace(/^#/, "")}`}
                            >
                              <Cross2Icon className="h-2.5 w-2.5" />
                            </button>
                          </span>
                        ))}
                      </div>
                    </div>
                  )
                })}
                <HashtagInput
                  onAdd={(tag) => {
                    const current = draft.hashtags ?? {}
                    const medium = current.medium ?? []
                    patchDraft({
                      hashtags: {
                        ...current,
                        medium: [...medium, tag],
                      },
                    })
                  }}
                />
              </div>
            </div>
          ) : null}

          {/* Social preview mock */}
          <div className="mx-auto w-full" style={{ maxWidth: `${previewMaxWidth}px` }}>
            {isHyperframeFormat ? (
              <div className="flex flex-col gap-3">
                <HyperFramePlayer draft={draft} brandId={brandProfileId ?? ""} />
                <div className="rounded-xl border border-border/70 bg-background/90 p-3">
                  <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                    Caption
                  </p>
                  <InlinePreviewTextarea
                    value={draft.captionPreview}
                    onChange={(event) => handleCaptionChange(event.target.value)}
                    placeholder="Write a caption..."
                    className="min-h-[5rem] text-sm leading-relaxed"
                  />
                </div>
              </div>
            ) : null}

            {!isHyperframeFormat && selectedPlatform === "instagram" ? (
              <div className="overflow-hidden rounded-[2.5rem] border-[5px] border-foreground/10 shadow-2xl">
                {/* Phone status bar */}
                <div className="relative flex items-center justify-center bg-background px-4 pt-3 pb-2">
                  <span className="absolute left-5 text-[9px] font-bold tabular-nums text-foreground/70">9:41</span>
                  <div className="h-5 w-[88px] rounded-full bg-foreground/90" />
                  <div className="absolute right-5 flex items-center gap-1 text-foreground/70">
                    <svg viewBox="0 0 24 24" className="h-3 w-3" fill="currentColor">
                      <path d="M1.5 8.5C5.082 4.918 9.795 3 12 3s6.918 1.918 10.5 5.5L21 11c-2.9-3.15-5.68-4.5-9-4.5S5.9 7.85 3 11L1.5 8.5z" />
                      <path d="M4.5 11.5C7.2 8.8 9.7 7.5 12 7.5s4.8 1.3 7.5 4L18 13c-1.9-2.15-3.7-3-6-3s-4.1.85-6 3L4.5 11.5z" />
                      <circle cx="12" cy="17" r="2" />
                    </svg>
                    <svg viewBox="0 0 24 24" className="h-3.5 w-3.5" fill="currentColor">
                      <rect x="1" y="6" width="18" height="12" rx="2" fillOpacity="0.3" />
                      <rect x="1" y="6" width="13" height="12" rx="2" />
                      <path d="M21 10v4a2 2 0 0 0 0-4z" />
                    </svg>
                  </div>
                </div>
                {/* Scrollable Instagram feed viewport */}
                <div
                  className="overflow-y-auto"
                  style={{ maxHeight: 560 }}
                >
                  <InstagramMobilePreview
                    draft={draftForPreview}
                    mediaAspectRatio={mediaAspectRatio}
                    onCaptionChange={handleCaptionChange}
                    thumbnailDirection={thumbnailDirection}
                    brandName={brandName}
                  />
                </div>
                {/* Home indicator */}
                <div className="flex justify-center bg-background py-2">
                  <div className="h-1 w-24 rounded-full bg-foreground/20" />
                </div>
              </div>
            ) : null}

            {!isHyperframeFormat && selectedPlatform === "facebook" ? (
              <FacebookFeedPreview
                draft={draftForPreview}
                mediaAspectRatio={mediaAspectRatio}
                onCaptionChange={handleCaptionChange}
                thumbnailDirection={thumbnailDirection}
                brandName={brandName}
              />
            ) : null}

            {!isHyperframeFormat && selectedPlatform === "linkedin" ? (
              <LinkedInDesktopPreview
                draft={draftForPreview}
                mediaAspectRatio={mediaAspectRatio}
                onCaptionChange={handleCaptionChange}
                thumbnailDirection={thumbnailDirection}
                brandName={brandName}
              />
            ) : null}

            {!isHyperframeFormat &&
            selectedPlatform !== "instagram" &&
            selectedPlatform !== "facebook" &&
            selectedPlatform !== "linkedin" ? (
              <div className="flex min-h-[24rem] items-center justify-center rounded-xl border border-dashed border-border/70 bg-muted/30 px-4 py-10">
                <p className="text-sm text-muted-foreground">
                  Preview for {selectedPlatform} is coming soon.
                </p>
              </div>
            ) : null}
          </div>
        </div>
      </ScrollArea>

      {/* Footer CTA */}
      {showFooter ? (
        <div className="shrink-0 border-t border-border/70 bg-background/90 p-3 flex flex-col gap-2">
          {tokenExpired && (
            <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-[12px] text-amber-700 dark:text-amber-300">
              Instagram access token expired.{" "}
              <a
                href="/settings?section=integrations"
                className="underline underline-offset-2"
              >
                Reconnect your account
              </a>
            </div>
          )}

          {onApprove && (
            <button
              type="button"
              disabled={isApproveDisabled}
              onClick={() => onApprove(draft.id)}
              className={cn(
                "flex w-full items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors",
                isApproveDisabled
                  ? "cursor-not-allowed bg-muted text-muted-foreground"
                  : "bg-primary text-primary-foreground hover:bg-primary/90"
              )}
            >
              {draft.status === "scheduled"
                ? "Approved for posting"
                : "Approve & Schedule"}
            </button>
          )}

          {canPublish && (
            <button
              type="button"
              disabled={isPublishing}
              onClick={() => publish(draft)}
              className={cn(
                "flex w-full items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors",
                isPublishing
                  ? "cursor-not-allowed bg-muted text-muted-foreground"
                  : "bg-primary text-primary-foreground hover:bg-primary/90"
              )}
            >
              {isPublishing ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  {stage === "container_created"
                    ? "Uploading media…"
                    : stage === "polling"
                      ? `Processing video${pollingAttempt > 0 ? ` (${pollingAttempt})` : ""}…`
                      : "Publishing…"}
                </>
              ) : (
                <>
                  <Send className="h-4 w-4" />
                  Publish to Instagram
                </>
              )}
            </button>
          )}

          {isPublished && (
            <div className="flex items-center justify-center gap-2 px-4 py-1.5">
              <span className="text-[12px] text-muted-foreground">Published</span>
              {draft.instagram_post_id && (
                <a
                  href={`https://www.instagram.com/p/${draft.instagram_post_id}/`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[12px] text-primary underline underline-offset-2"
                >
                  View on Instagram
                </a>
              )}
            </div>
          )}
        </div>
      ) : null}
    </div>
  )
}

const CAPTION_LIMITS: Record<string, number> = {
  instagram: 2200,
  facebook: 63206,
  linkedin: 3000,
}

function CaptionCharCount({ caption, platform }: { caption: string; platform: string }) {
  const limit = CAPTION_LIMITS[platform] ?? 2200
  const len = caption.length
  return (
    <div className="mt-1 flex justify-end">
      <span
        className={cn(
          "text-[10px] tabular-nums",
          len > limit
            ? "text-destructive"
            : len > limit * 0.9
              ? "text-amber-600"
              : "text-muted-foreground/50"
        )}
      >
        {len.toLocaleString()} / {limit.toLocaleString()}
      </span>
    </div>
  )
}

function InstagramMobilePreview({
  draft,
  mediaAspectRatio,
  onCaptionChange,
  thumbnailDirection,
  brandName,
}: SocialPreviewProps) {
  const slides = React.useMemo(() => resolveCarouselSlides(draft), [
    draft.publishingAssets,
    draft.mediaSuggestion,
  ])
  const mediaAltText = React.useMemo(() => resolveDraftMediaAltText(draft), [
    draft.mediaSuggestion,
    draft.title,
  ])
  const displayName = brandName ?? "Your Brand"
  const initials = brandInitials(brandName)

  return (
    <div className="w-full overflow-hidden bg-card text-foreground">
      <div className="flex items-center p-3 border-b border-border/70">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-primary/70 via-accent/70 to-secondary/70 p-[2px] flex items-center justify-center text-[10px] font-bold text-foreground">
            <div className="flex h-full w-full items-center justify-center rounded-full bg-background">
              <div className="flex h-7 w-7 items-center justify-center rounded-full bg-muted text-[8px] text-muted-foreground">
                {initials}
              </div>
            </div>
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-semibold leading-none tracking-tight">
              {displayName}
            </span>
            <span className="mt-1 text-[10px] text-muted-foreground">Sponsored</span>
          </div>
        </div>
      </div>

      <CarouselMediaArea slides={slides} alt={mediaAltText} aspectRatio={mediaAspectRatio} />

      {thumbnailDirection ? (
        <div className="border-b border-border/70 px-3 py-2">
          <p className="line-clamp-2 text-[11px] text-muted-foreground">
            Thumbnail: {thumbnailDirection}
          </p>
        </div>
      ) : null}

      {/* Engagement bar */}
      <div className="flex items-center justify-between border-b border-border/40 px-3 py-2">
        <div className="flex items-center gap-4 text-muted-foreground/40">
          <svg viewBox="0 0 24 24" className="h-5 w-5 cursor-default" fill="none" stroke="currentColor" strokeWidth={2}><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" /></svg>
          <svg viewBox="0 0 24 24" className="h-5 w-5 cursor-default" fill="none" stroke="currentColor" strokeWidth={2}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>
          <svg viewBox="0 0 24 24" className="h-5 w-5 cursor-default" fill="none" stroke="currentColor" strokeWidth={2}><line x1="22" y1="2" x2="11" y2="13" /><polygon points="22 2 15 22 11 13 2 9 22 2" /></svg>
        </div>
        <svg viewBox="0 0 24 24" className="h-5 w-5 cursor-default text-muted-foreground/40" fill="none" stroke="currentColor" strokeWidth={2}><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" /></svg>
      </div>

      <div className="px-3 pb-3 pt-2">
        <p className="mb-1 text-xs font-bold">{displayName}</p>
        <InlinePreviewTextarea
          value={draft.captionPreview}
          onChange={(event) => onCaptionChange(event.target.value)}
          aria-label="Instagram caption"
          className="min-h-[7rem] border-0 bg-transparent p-0 text-xs leading-relaxed focus-visible:ring-0"
          placeholder="Write your caption..."
        />
        <CaptionCharCount caption={draft.captionPreview} platform="instagram" />
      </div>
    </div>
  )
}

function FacebookFeedPreview({
  draft,
  mediaAspectRatio,
  onCaptionChange,
  thumbnailDirection,
  brandName,
}: SocialPreviewProps) {
  const slides = React.useMemo(() => resolveCarouselSlides(draft), [
    draft.publishingAssets,
    draft.mediaSuggestion,
  ])
  const mediaAltText = React.useMemo(() => resolveDraftMediaAltText(draft), [
    draft.mediaSuggestion,
    draft.title,
  ])
  const displayName = brandName ?? "Your Brand"

  return (
    <div className="w-full overflow-hidden rounded-xl border border-border/70 bg-card shadow-lg text-foreground">
      <div className="p-3 flex items-center border-b border-border/70">
        <div className="flex items-center gap-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-full border border-primary/30 bg-primary/15 font-bold text-primary">
            {brandInitials(brandName)}
          </div>
          <div>
            <p className="text-sm font-bold tracking-tight">{displayName}</p>
            <p className="text-[11px] text-muted-foreground">Sponsored · 1h</p>
          </div>
        </div>
      </div>

      <div className="px-4 py-3 space-y-2">
        <InlinePreviewTextarea
          value={draft.captionPreview}
          onChange={(event) => onCaptionChange(event.target.value)}
          aria-label="Facebook post copy"
          className="min-h-[7rem] border-0 bg-transparent p-0 text-sm leading-relaxed focus-visible:ring-0"
          placeholder="Write your post copy..."
        />
        <CaptionCharCount caption={draft.captionPreview} platform="facebook" />
      </div>

      <CarouselMediaArea slides={slides} alt={mediaAltText} aspectRatio={mediaAspectRatio} borderClass="border-y border-border/70" />

      {thumbnailDirection ? (
        <div className="border-t border-border/70 px-4 py-2">
          <p className="line-clamp-2 text-[11px] text-muted-foreground">
            Thumbnail: {thumbnailDirection}
          </p>
        </div>
      ) : null}

      {/* Engagement bar */}
      <div className="flex items-center gap-4 border-t border-border/40 px-4 py-2 text-[12px] font-medium text-muted-foreground/40 cursor-default">
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z" /></svg>
          Like
        </span>
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>
          Comment
        </span>
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><line x1="8.59" y1="13.51" x2="15.42" y2="17.49" /><line x1="15.41" y1="6.51" x2="8.59" y2="10.49" /></svg>
          Share
        </span>
      </div>
    </div>
  )
}

function LinkedInDesktopPreview({
  draft,
  mediaAspectRatio,
  onCaptionChange,
  thumbnailDirection,
  brandName,
}: SocialPreviewProps) {
  const slides = React.useMemo(() => resolveCarouselSlides(draft), [
    draft.publishingAssets,
    draft.mediaSuggestion,
  ])
  const mediaAltText = React.useMemo(() => resolveDraftMediaAltText(draft), [
    draft.mediaSuggestion,
    draft.title,
  ])
  const displayName = brandName ?? "Your Brand"

  return (
    <div className="w-full overflow-hidden rounded-xl border border-border/70 bg-card shadow-lg text-foreground">
      <div className="p-3 flex items-center justify-between border-b border-border/70">
        <div className="flex items-center gap-2">
          <div className="flex h-11 w-11 items-center justify-center rounded border border-primary/30 bg-primary/15 text-lg font-bold text-primary">
            {brandInitials(brandName)}
          </div>
          <div>
            <p className="text-sm font-bold tracking-tight">{displayName}</p>
            <p className="text-[11px] text-muted-foreground">12,450 followers</p>
          </div>
        </div>
      </div>

      <div className="px-4 py-3">
        <InlinePreviewTextarea
          value={draft.captionPreview}
          onChange={(event) => onCaptionChange(event.target.value)}
          aria-label="LinkedIn post copy"
          className="min-h-[7rem] border-0 bg-transparent p-0 text-sm leading-relaxed focus-visible:ring-0"
          placeholder="Write your post copy..."
        />
        <CaptionCharCount caption={draft.captionPreview} platform="linkedin" />
      </div>

      <CarouselMediaArea slides={slides} alt={mediaAltText} aspectRatio={mediaAspectRatio} borderClass="border-y border-border/70" />

      {thumbnailDirection ? (
        <div className="border-t border-border/70 px-4 py-2">
          <p className="line-clamp-2 text-[11px] text-muted-foreground">
            Thumbnail: {thumbnailDirection}
          </p>
        </div>
      ) : null}

      {/* Engagement bar */}
      <div className="flex items-center gap-4 border-t border-border/40 px-4 py-2 text-[12px] font-medium text-muted-foreground/40 cursor-default">
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z" /></svg>
          Like
        </span>
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg>
          Comment
        </span>
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><polyline points="17 1 21 5 17 9" /><path d="M3 11V9a4 4 0 0 1 4-4h14" /><polyline points="7 23 3 19 7 15" /><path d="M21 13v2a4 4 0 0 1-4 4H3" /></svg>
          Repost
        </span>
        <span className="flex items-center gap-1">
          <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2}><line x1="22" y1="2" x2="11" y2="13" /><polygon points="22 2 15 22 11 13 2 9 22 2" /></svg>
          Send
        </span>
      </div>
    </div>
  )
}
