import { z } from 'zod';
import { paidAdFunnelStageSchema } from './brief';

// The Library tag that marks a creative as ready to be launched as a paid ad. The
// creative sub-agent applies it (Phase 1); the optimizer pulls creatives carrying
// it when a human launches a PAUSED ad (Phase 2). Kept here so the sub-agent, the
// optimizer, and the Frontend all agree on one literal — never re-typed per side.
export const AD_READY_TAG = 'ad-ready';

// How a creative earned its ad-ready tag.
export const adIntentSourceSchema = z.enum([
  // Net-new video generated by the creative sub-agent.
  'generated',
  // An existing winning organic creative promoted into paid (asset row reused).
  'organic_promotion',
]);
export type AdIntentSource = z.infer<typeof adIntentSourceSchema>;

// Provenance carried alongside an ad-ready creative: WHY it is ad-ready and the
// grounded decisions behind it. Travels on the `ad_ready_tagged` run frame and is
// available to the optimizer at launch. Loose object — an extra key never fails parse.
export const adIntentSchema = z.object({
  objective: z.string(),
  funnelStage: paidAdFunnelStageSchema,
  angle: z.string(),
  hook: z.string(),
  // 0-100 virality overall that cleared the gate; null if the score was pending.
  viralityScore: z.number().min(0).max(100).nullable().default(null),
  source: adIntentSourceSchema,
  // The paid-creative run that produced this; null for ad-hoc tags.
  sourceRunId: z.string().nullable().default(null),
  // For promotions: the winning organic media.assets id this ad reuses.
  sourceOrganicAssetId: z.string().nullable().default(null),
});
export type AdIntent = z.infer<typeof adIntentSchema>;
